# Generated by Django 5.0.8 on 2026-07-15 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0004_remove_cycle_nombre_sujets_actuels_migration_and_more'),
        ('depenses', '0004_routinedepense_routineappliquee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_produit', models.CharField(choices=[('ALIMENT', 'Aliment'), ('MEDICAMENT', 'Médicament'), ('VACCIN', 'Vaccin'), ('LITIERE', 'Litière'), ('AUTRE', 'Autre')], default='ALIMENT', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unite', models.CharField(default='kg', max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_stock_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit en stock',
                'verbose_name_plural': 'Produits en stock',
                'db_table': 'produits_stock',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_crees', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='cycles.cycle')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='depenses.depense')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produitstock')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvements_stock',
                'ordering': ['-date'],
            },
        ),
    ]
