# Generated by Django 5.0.8 on 2026-07-10 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OEUFS', "Vente d'œufs"), ('POULETS', 'Vente de poulets'), ('POULE_REFORME', 'Vente de poules de réforme'), ('POUSSINS', 'Vente de poussins'), ('FIANTES', 'Vente de fientes'), ('AUTRE', 'Autre')], max_length=20)),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('facture_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('facture_photo', models.URLField(blank=True, null=True)),
                ('signature', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('remboursement_confirme', models.BooleanField(default=False)),
                ('remboursement_cycle_id', models.UUIDField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_crees', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'ventes',
                'ordering': ['-date'],
            },
        ),
    ]
