# Generated by Django 5.0.8 on 2026-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='prix_unitaire',
            field=models.FloatField(),
        ),
    ]
