# Generated by Django 5.0.8 on 2026-07-15 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_vente_prix_unitaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='annonce_id',
            field=models.UUIDField(blank=True, help_text="ID de l'annonce marketplace liée", null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vente',
            name='vendeur',
            field=models.CharField(blank=True, help_text='Nom du vendeur (si différent du propriétaire)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TypeVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_vente_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de vente',
                'verbose_name_plural': 'Types de ventes',
                'db_table': 'types_vente',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='type_vente',
            field=models.ForeignKey(blank=True, help_text='Type de vente personnalisé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='ventes.typevente'),
        ),
    ]
