# Generated by Django 5.0.8 on 2026-07-10 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('ALIMENT', 'Aliment'), ('POUSSIN', 'Achat de poussins'), ('VACCIN', 'Vaccins et médicaments'), ('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('MAIN_OEUVRE', "Main-d'œuvre"), ('TRANSPORT', 'Transport'), ('ENTRETIEN', 'Entretien'), ('EQUIPEMENT', 'Équipement'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('facture_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('facture_photo', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'depenses',
                'ordering': ['-date'],
            },
        ),
    ]
