# Generated by Django 5.0.8 on 2026-07-15 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='est_depense_routine',
            field=models.BooleanField(default=False, help_text='Dépense générée automatiquement'),
        ),
        migrations.AddField(
            model_name='depense',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='depense',
            name='routine_id',
            field=models.UUIDField(blank=True, help_text='ID de la routine parente', null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône Flutter", max_length=50, null=True)),
                ('couleur', models.CharField(blank=True, help_text='Code couleur hex (#FF0000)', max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_depense_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'db_table': 'categories_depense',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie_depense',
            field=models.ForeignKey(blank=True, help_text='Catégorie personnalisée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.categoriedepense'),
        ),
    ]
