# Generated by Django 5.0.8 on 2026-07-15 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_cycle_est_publie_marketplace_cycle_metadata_and_more'),
        ('depenses', '0003_depense_est_depense_routine_depense_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDepense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: Achat poussins, Vaccin J21, Aliment démarrage', max_length=100)),
                ('age_jour', models.IntegerField(default=0, help_text='Âge du cycle auquel appliquer cette routine')),
                ('mode_calcul', models.CharField(choices=[('PAR_SUJET', 'Par sujet'), ('PAR_TRANCHE', 'Par tranche (ex: 1 sac pour X poulets)'), ('FIXE', 'Montant fixe')], default='PAR_SUJET', max_length=20)),
                ('montant_par_sujet', models.DecimalField(decimal_places=0, default=0, help_text='Montant par sujet si mode PAR_SUJET', max_digits=10)),
                ('seuil_tranche', models.IntegerField(default=50, help_text='Nombre de poulets par tranche (ex: 1 sac pour 50 poulets)')),
                ('montant_par_tranche', models.DecimalField(decimal_places=0, default=0, help_text='Montant par tranche si mode PAR_TRANCHE', max_digits=10)),
                ('montant_fixe', models.DecimalField(decimal_places=0, default=0, help_text='Montant fixe si mode FIXE', max_digits=10)),
                ('est_obligatoire', models.BooleanField(default=False, help_text='Si vrai, appliqué automatiquement sans confirmation')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie_depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='depenses.categoriedepense')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines_depense_crees', to=settings.AUTH_USER_MODEL)),
                ('type_poulet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines_depense', to='cycles.typepoulet')),
            ],
            options={
                'verbose_name': 'Routine de dépense',
                'verbose_name_plural': 'Routines de dépenses',
                'db_table': 'routines_depense',
                'ordering': ['type_poulet', 'age_jour'],
            },
        ),
        migrations.CreateModel(
            name='RoutineAppliquee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_calcule', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nb_poulets_au_moment', models.IntegerField()),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('confirmee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines_appliquees', to='cycles.cycle')),
                ('depense_generee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_source', to='depenses.depense')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='depenses.routinedepense')),
            ],
            options={
                'verbose_name': 'Routine appliquée',
                'verbose_name_plural': 'Routines appliquées',
                'db_table': 'routines_appliquees',
                'ordering': ['-date_application'],
                'unique_together': {('routine', 'cycle')},
            },
        ),
    ]
