# Generated by Django 5.0.8 on 2026-07-10 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poulailler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('longueur', models.FloatField(help_text='Longueur en mètres')),
                ('largeur', models.FloatField(help_text='Largeur en mètres')),
                ('hauteur', models.FloatField(blank=True, help_text='Hauteur en mètres', null=True)),
                ('localisation', models.CharField(blank=True, max_length=200, null=True)),
                ('type_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_mangeoires', models.IntegerField(default=0)),
                ('nombre_abreuvoirs', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poulaillers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poulailler',
                'verbose_name_plural': 'Poulaillers',
                'db_table': 'poulaillers',
                'ordering': ['nom'],
            },
        ),
    ]
