# Generated by Django 5.0.8 on 2026-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poulaillers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poulailler',
            name='capacite_max_recommandee',
            field=models.IntegerField(blank=True, help_text='Capacité max recommandée selon le type', null=True),
        ),
        migrations.AddField(
            model_name='poulailler',
            name='cout_construction',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='poulailler',
            name='date_construction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poulailler',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
