# Generated by Django 6.0.6 on 2026-07-06 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportSuivi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('aliment_consomme', models.DecimalField(decimal_places=2, default=0, help_text="Quantité d'aliment consommée en kg", max_digits=10)),
                ('eau_consommee', models.DecimalField(decimal_places=2, default=0, help_text="Quantité d'eau consommée en litres", max_digits=10)),
                ('maladie_observee', models.CharField(blank=True, help_text='Maladie observée (ex: Coccidiose, Gumboro, etc.)', max_length=100, null=True)),
                ('medicaments_administres', models.TextField(blank=True, help_text='Médicaments administrés avec dosages', null=True)),
                ('nb_sujets_malades', models.IntegerField(default=0)),
                ('observations', models.TextField(blank=True, help_text='Observations générales (comportement, conditions, etc.)', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'Rapport de suivi',
                'verbose_name_plural': 'Rapports de suivi',
                'db_table': 'rapports_suivi',
                'ordering': ['-periode_fin'],
            },
        ),
    ]
