# Generated by Django 5.0.8 on 2026-07-10 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportSuivi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('aliment_consomme', models.DecimalField(decimal_places=2, default=0, help_text="Quantité d'aliment consommée en kg", max_digits=10)),
                ('eau_consommee', models.DecimalField(decimal_places=2, default=0, help_text="Quantité d'eau consommée en litres", max_digits=10)),
                ('maladie_observee', models.CharField(blank=True, help_text='Maladie observée (ex: Coccidiose, Gumboro, etc.)', max_length=100, null=True)),
                ('medicaments_administres', models.TextField(blank=True, help_text='Médicaments administrés avec dosages', null=True)),
                ('nb_sujets_malades', models.IntegerField(default=0)),
                ('observations', models.TextField(blank=True, help_text='Observations générales (comportement, conditions, etc.)', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rapport de suivi',
                'verbose_name_plural': 'Rapports de suivi',
                'db_table': 'rapports_suivi',
                'ordering': ['-periode_fin'],
            },
        ),
    ]
