# Generated by Django 5.0.8 on 2026-07-15 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportsuivi',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rapportsuivi',
            name='mortalites_periode',
            field=models.IntegerField(default=0, help_text='Nombre de morts dans la période'),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='maladie_observee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='medicaments_administres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TypeMaladie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptomes', models.TextField(blank=True, null=True)),
                ('traitement_recommande', models.TextField(blank=True, null=True)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_maladie_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de maladie',
                'verbose_name_plural': 'Types de maladies',
                'db_table': 'types_maladie',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='rapportsuivi',
            name='type_maladie',
            field=models.ForeignKey(blank=True, help_text='Type de maladie identifié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='rapports.typemaladie'),
        ),
    ]
