# Generated by Django 5.0.8 on 2026-07-15 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_remove_cycle_nombre_sujets_actuels_migration_and_more'),
        ('rapports', '0003_rapportsuivi_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportsuivi',
            name='sous_bande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='cycles.sousbande'),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='maladie_observee',
            field=models.CharField(blank=True, help_text='Maladie observée (ex: Coccidiose, Gumboro, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='medicaments_administres',
            field=models.TextField(blank=True, help_text='Médicaments administrés avec dosages', null=True),
        ),
        migrations.AlterField(
            model_name='rapportsuivi',
            name='observations',
            field=models.TextField(blank=True, help_text='Observations générales (comportement, conditions, etc.)', null=True),
        ),
    ]
