# Generated by Django 5.0.8 on 2026-07-15 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(help_text='Nom de la table concernée', max_length=100)),
                ('object_id', models.CharField(help_text="ID de l'objet modifié", max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('data', models.JSONField(help_text="Données complètes de l'objet")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SYNCED', 'Synchronisé'), ('FAILED', 'Échoué')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synchronisation en attente',
                'verbose_name_plural': 'Synchronisations en attente',
                'db_table': 'pending_sync',
                'ordering': ['created_at'],
            },
        ),
    ]
