# Generated by Django 6.0.6 on 2026-07-06 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preteur', models.CharField(max_length=100)),
                ('type_preteur', models.CharField(choices=[('BANQUE', 'Banque'), ('MICROFINANCE', 'Microfinance'), ('FAMILLE', 'Famille'), ('TONTINE', 'Tontine'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_deblocage', models.DateField()),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mode_remboursement', models.CharField(choices=[('IMPOSE', 'Échéances imposées'), ('PROPOSE', 'Échéances proposées')], max_length=20)),
                ('duree_totale_mois', models.IntegerField(blank=True, null=True)),
                ('periodicite', models.CharField(blank=True, max_length=20, null=True)),
                ('montant_restant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_rembourse', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_crees', to=settings.AUTH_USER_MODEL)),
                ('cycles_affectes', models.ManyToManyField(blank=True, related_name='prets', to='cycles.cycle')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'db_table': 'prets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_echeance', models.DateField()),
                ('montant_due', models.DecimalField(decimal_places=0, max_digits=12)),
                ('est_payee', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='prets.pret')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'db_table': 'echeances',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementPret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='Source du remboursement: vente_cycle, manuel, etc.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_manually_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_crees', to=settings.AUTH_USER_MODEL)),
                ('cycle_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_prets', to='cycles.cycle')),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='prets.echeance')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='prets.pret')),
                ('vente_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_prets', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'remboursements',
                'ordering': ['-date'],
            },
        ),
    ]
