# Generated by Django 5.0.8 on 2026-07-10 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0002_initial'),
        ('prets', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='cycles_affectes',
            field=models.ManyToManyField(blank=True, related_name='prets', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='echeance',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='prets.pret'),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='cycle_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_prets', to='cycles.cycle'),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='echeance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='prets.echeance'),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='prets.pret'),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='vente_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_prets', to='ventes.vente'),
        ),
    ]
