# Generated by Django 5.0.8 on 2026-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='echeance',
            name='transaction_mobile_id',
            field=models.UUIDField(blank=True, help_text='ID de la transaction mobile associée', null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
