# Generated by Django 5.0.8 on 2026-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0003_echeance_metadata_echeance_transaction_mobile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='type_taux',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=10),
        ),
    ]
