# Generated by Django 5.0.8 on 2026-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0004_pret_date_limite_pret_type_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='transaction_mobile_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remboursementpret',
            name='transaction_mobile_id',
            field=models.UUIDField(blank=True, help_text='ID de la transaction mobile associée', null=True),
        ),
    ]
