# Generated by Django 5.0.8 on 2026-07-10 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CHAIR', 'Poulet de chair'), ('PONDEUSE', 'Poule pondeuse'), ('LOCAL', 'Poulet local'), ('AUTRE', 'Autre')], default='CHAIR', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nombre_sujets_initiaux', models.IntegerField()),
                ('nombre_sujets_actuels', models.IntegerField()),
                ('duree_estimee_jours', models.IntegerField(help_text='Durée estimée du cycle en jours')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycles',
                'ordering': ['-date_debut'],
            },
        ),
    ]
