# Generated by Django 5.0.8 on 2026-07-15 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='est_publie_marketplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cycle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TypePoulet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_estimee_jours', models.IntegerField(default=45, help_text='Durée standard du cycle pour ce type')),
                ('densite_recommandee', models.FloatField(default=8.0, help_text='Densité recommandée en poulets/m²')),
                ('prix_poussin_moyen', models.DecimalField(decimal_places=0, default=0, help_text="Prix moyen d'un poussin", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_poulet_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de poulet',
                'verbose_name_plural': 'Types de poulets',
                'db_table': 'types_poulet',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='type_poulet',
            field=models.ForeignKey(blank=True, help_text='Type de poulet personnalisé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='cycles.typepoulet'),
        ),
    ]
