# Generated by Django 5.0.8 on 2026-07-15 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_cycle_est_publie_marketplace_cycle_metadata_and_more'),
        ('poulaillers', '0003_poulailler_capacite_max_recommandee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='nombre_sujets_actuels',
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sujets', models.IntegerField()),
                ('age_sujets', models.IntegerField(help_text='Âge des poulets au moment de la migration')),
                ('raison', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_crees', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='cycles.cycle')),
                ('poulailler_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations_entrantes', to='poulaillers.poulailler')),
                ('poulailler_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations_sortantes', to='poulaillers.poulailler')),
            ],
            options={
                'verbose_name': 'Migration',
                'verbose_name_plural': 'Migrations',
                'db_table': 'migrations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SousBande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sujets', models.IntegerField()),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_bandes', to='cycles.cycle')),
                ('poulailler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_bandes', to='poulaillers.poulailler')),
            ],
            options={
                'verbose_name': 'Sous-bande',
                'verbose_name_plural': 'Sous-bandes',
                'db_table': 'sous_bandes',
                'ordering': ['date_creation'],
            },
        ),
    ]
