# Generated by Django 5.0.8 on 2026-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_remove_cycle_nombre_sujets_actuels_migration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='nb_morts',
            field=models.IntegerField(default=0, help_text='Nombre de sujets morts (maladie, accident)'),
        ),
    ]
