# Generated by Django 5.0.8 on 2026-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_cycle_nb_morts'),
    ]

    operations = [
        migrations.AddField(
            model_name='typepoulet',
            name='nb_abreuvoirs',
            field=models.IntegerField(default=0, help_text="Nombre d'abreuvoirs utilisés pour ce cycle"),
        ),
        migrations.AddField(
            model_name='typepoulet',
            name='nb_mangeoires',
            field=models.IntegerField(default=0, help_text='Nombre de mangeoires utilisées pour ce cycle'),
        ),
    ]
