# Generated by Django 5.0.8 on 2026-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0006_typepoulet_nb_abreuvoirs_typepoulet_nb_mangeoires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typepoulet',
            name='nb_abreuvoirs',
        ),
        migrations.RemoveField(
            model_name='typepoulet',
            name='nb_mangeoires',
        ),
        migrations.AddField(
            model_name='cycle',
            name='nb_abreuvoirs',
            field=models.IntegerField(default=0, help_text="Nombre d'abreuvoirs utilisés pour ce cycle"),
        ),
        migrations.AddField(
            model_name='cycle',
            name='nb_mangeoires',
            field=models.IntegerField(default=0, help_text='Nombre de mangeoires utilisées pour ce cycle'),
        ),
    ]
