# Generated by Django 5.0.8 on 2026-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Données supplémentaires flexibles'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_money_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone mobile money', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('OM', 'Orange Money'), ('MOMO', 'MTN Mobile Money'), ('AUTRE', 'Autre')], help_text='Fournisseur de paiement mobile', max_length=20, null=True),
        ),
    ]
