# Generated by Django 5.0.8 on 2026-07-15 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_metadata_user_mobile_money_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ParametreUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence_rappel_rapport', models.IntegerField(default=7, help_text='Fréquence de rappel en jours pour soumettre un rapport')),
                ('rappel_rapport_actif', models.BooleanField(default=True, help_text='Recevoir des rappels pour soumettre un rapport')),
                ('notif_echeance_pret', models.BooleanField(default=True)),
                ('notif_densite', models.BooleanField(default=True)),
                ('notif_consommation', models.BooleanField(default=True)),
                ('notif_fin_cycle', models.BooleanField(default=True)),
                ('unite_aliment', models.CharField(default='kg', max_length=10)),
                ('unite_eau', models.CharField(default='L', max_length=10)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre utilisateur',
                'verbose_name_plural': 'Paramètres utilisateurs',
                'db_table': 'parametres_utilisateur',
            },
        ),
    ]
